name: CI

on:
  push:
    branches:
      - master

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
      name: Login to Docker
      uses: docker/login-action@v1
      with:
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    -
      name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        tags: francium/hello-django:latest
        push: true
    -
      name: Image digest
      run echo ${{steps.docker_build.outputs.digest}}
